import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { PropsWithChildren } from "react";
import { ThemeToggle } from "../_components/ThemeToggle";
import { ThemeProvider } from "../_providers/ThemeProvider";
import "../_styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<PropsWithChildren>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-background text-foreground antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="absolute top-3 right-3 z-50 opacity-67 hover:opacity-100 transition-opacity">
            <ThemeToggle />
          </div>

          <div className="items-center justify-items-center min-h-screen p-8 pb-20 sm:p-20">
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
