import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { PropsWithChildren } from "react";
import { ThemeToggle } from "../_components/ThemeToggle";
import { ThemeProvider } from "../_providers/ThemeProvider";
import { NotificationsProvider } from "../_providers/NotificationsProvider";
import { Notifications } from "../_components/Notifications";
import "../_styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<PropsWithChildren>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-background text-foreground antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NotificationsProvider>
            <div className="absolute top-3 right-3 z-50 flex items-center gap-2">
              <Notifications />

              <ThemeToggle />
            </div>

            <div className="items-center justify-items-center min-h-screen p-8 pb-20 sm:p-20">
              {children}
            </div>
          </NotificationsProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
